# Datos generales.
logging="INFO"
network-id=1337
identity="nodo_principal"
node-private-key-file="/nodo1/key"

# Archivos de configuración.
data-path="/var/lib/besu"
genesis-file="/genesis.json"

# Conexiones de la red.
nat-method=["DOCKER"]
host-allowlist=["*"]

# Activar el minado de bloques.
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

# Configurar las comunicaciones.
p2p-host="0.0.0.0"
p2p-port=30303
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ADMIN", "CLIQUE","ETH","NET", "TXPOOL", "WEB3"]
rpc-http-cors-origins=["*"]
